name: Pipeline

on:
  pull_request:
    branches: [master]

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Instalar Java 25
        uses: actions/setup-java@v5.0.0
        with:
          distribution: "temurin"
          java-version: 25

      - name: Empacotamento do projeto
        run: mvn -B clean package -DskipTests

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Instalar Java 25
        uses: actions/setup-java@v5.0.0
        with:
          distribution: "temurin"
          java-version: 25

      - name: Testes Unitários
        run: mvn -B verify

      - name: Upload do relátório do JaCoCo
        uses: actions/upload-artifact@v5.0.0
        with:
          name: jacoco-report
          path: target/site/jacoco

  format:
    name: Format Code
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.ref}}
          fetch-depth: 0

      - name: Instalar Java 25
        uses: actions/setup-java@v5.0.0
        with:
          distribution: "temurin"
          java-version: 25
      - name: Formatar código com Spotless
        run: ./mvnw spotless:apply

      - name: Faz um commit e push das mudanças
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Aplica formatação do spotless"
            git push
          else
            echo "Nenhuma mudança de formatação necessária."
          fi
